POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.PNG"
Content-Type: image/png

< ./input.PNG

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

nazwa_albumu
------FormBoundary1234


### Rejestracja użytkownika 

POST http://localhost:3000/api/user/register HTTP/1.1

{    
   "name": "name",
   "lastName": "lastName",
   "email":"mateusz.czek332@gmail.com",
   "password":"pass"
}

