POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.PNG"
Content-Type: image/png

< ./input.PNG

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

nazwa_albumu
------FormBoundary1234


### Rejestracja użytkownika 

POST http://localhost:3000/api/user/register HTTP/1.1

{    
   "name": "name1234",
   "lastName": "lastName",
   "email":"mateusz.czek332@gmail.com",
   "password":"pass"
}

### Logowanie 
POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{
  "email":"mateusz.czek332@gmail.com",
  "password":"pass"
}

### Potwierdzenie rejestracji

POST http://localhost:3000/api/user/confirm/ HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoibWF0ZXVzei5jemVrMzMyQGdtYWlsLmNvbSIsImlhdCI6MTY1MzgzMDk3OSwiZXhwIjoxNjUzODM0NTc5fQ.Vn7z0RpVu7UqwskjUOlMZ7NprJzpezWYhcXUapMNX1A


### Potwierdzenie rejestracji przez link

GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoibWF0ZXVzei5jemVrMzMyQGdtYWlsLmNvbSIsImlhdCI6MTY1MzgxNTgzMCwiZXhwIjoxNjUzODE5NDMwfQ.RzkE6OregZ_Ws6IA8rUIxCBpZhhBTlPDObJxFOiUqzQ  HTTP/1.1

### Pobranie danych o uzytkowniku 

GET http://localhost:3000/api/user HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTM4MzE4MzAsImV4cCI6MTY1MzkxODIzMH0.vZxWofad_uv6wduh2eB6sSlu37suyaziQAuzq_Ed5Ys

### Zmiana danych user'a

PATCH http://localhost:3000/api/user HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTM4MzE4MzAsImV4cCI6MTY1MzkxODIzMH0.vZxWofad_uv6wduh2eB6sSlu37suyaziQAuzq_Ed5Ys

{
  "name": "newName",
  "lastName": "newLastName"
}

### Loguot

GET http://localhost:3000/api/user/logout HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTM4MzE4MzAsImV4cCI6MTY1MzkxODIzMH0.vZxWofad_uv6wduh2eB6sSlu37suyaziQAuzq_Ed5Ys