### Rejestracja użytkownika 

POST http://localhost:3000/api/user/register HTTP/1.1

{    
   "name": "name1234",
   "lastName": "lastName",
   "email":"mateusz.czek332@gmail.com",
   "password":"pass"
}

### Logowanie 
POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{
  "email":"mateusz.czek332@gmail.com",
  "password":"pass"
}

### Potwierdzenie rejestracji

POST http://localhost:3000/api/user/confirm/ HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoibWF0ZXVzei5jemVrMzMyQGdtYWlsLmNvbSIsImlhdCI6MTY1NDAxMTE3NSwiZXhwIjoxNjU0MDE0Nzc1fQ.XQ7PZb7RT7zVVbghygxkEn_6DHSvofKJEiIPFx25pI4


### Potwierdzenie rejestracji przez link

GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoibWF0ZXVzei5jemVrMzMyQGdtYWlsLmNvbSIsImlhdCI6MTY1MzgxNTgzMCwiZXhwIjoxNjUzODE5NDMwfQ.RzkE6OregZ_Ws6IA8rUIxCBpZhhBTlPDObJxFOiUqzQ  HTTP/1.1

### Pobranie danych o uzytkowniku 

GET http://localhost:3000/api/user HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTM4MzE4MzAsImV4cCI6MTY1MzkxODIzMH0.vZxWofad_uv6wduh2eB6sSlu37suyaziQAuzq_Ed5Ys

### Zmiana danych user'a

PATCH http://localhost:3000/api/user HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTM4MzE4MzAsImV4cCI6MTY1MzkxODIzMH0.vZxWofad_uv6wduh2eB6sSlu37suyaziQAuzq_Ed5Ys

{
  "name": "newName",
  "lastName": "newLastName"
}

### Loguot

GET http://localhost:3000/api/user/logout HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTM4MzE4MzAsImV4cCI6MTY1MzkxODIzMH0.vZxWofad_uv6wduh2eB6sSlu37suyaziQAuzq_Ed5Ys

### CZĘŚĆ 1 - zdjecia 
### Post obrazka

POST http://localhost:3000/api/photos HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTM5Mzg0MTUsImV4cCI6MTY1NDAyNDgxNX0.U4qISv2Zz-hD9ayrMmmHAzRB0xiG2BAQ1J6z7nRhgCg
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.PNG"
Content-Type: image/png

< ./input.PNG

------FormBoundary1234

### Get wszystkich zdjec

GET http://localhost:3000/api/photos HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

### Get jednego zdjecia 

GET http://localhost:3000/api/photos/1654018910362 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

### Patch jsona

PATCH http://localhost:3000/api/photos/1654011305634 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

{
  "status": "zmienione 2"
}

### delete zdjecia

DELETE http://localhost:3000/api/photos/1654012585624 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

### TAGI
### Popranie tablicy tagow - stringi
GET http://localhost:3000/api/tags/raw HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

### Popranie tablicy tagow - jsony
GET http://localhost:3000/api/tags HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

### Popranie jednego taga
GET http://localhost:3000/api/tags/1 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

### Dodanie nowego taga
POST http://localhost:3000/api/tags HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

{   
  "name":"#nowytag",
  "popularity": 1000000    
}

### Interagcja tagów i zdjec
### Dodawanie pojedynczego taga do zdjecia 

PATCH http://localhost:3000/api/photos/tags/1654018910362 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

{    
  "id": 99,
  "name": "#XDDDDD",
  "popularity": 999999
}

### Dodawanie pojedynczego taga do zdjecia 

PATCH http://localhost:3000/api/photos/tags/mass/1654018910362 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U

[
  {
    "id": 0,
    "name": "#love",
    "popularity": 242
  },
  {
    "id": 1,
    "name": "#instagood",
    "popularity": 433
  }
]

### Get tagow podanego zdjecia 

GET http://localhost:3000/api/photos/tags/1654018910362 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1c3ouY3plazMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NTQwMTExOTEsImV4cCI6MTY1NDA5NzU5MX0.5XQVMWlN0IjXh-suonIEJjhyzLOwm5YhR2XH1uYiI8U
